"use strict";

// Generated by thriftgo 0.4.2-HuiDu(v1.3)
// Source: test\typescript\test_expreq.thrift
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

/**
 * IExpreq 异步接口
 * 用于 Axios 客户端等异步实现
 */
export interface IExpreq {
  add(a: TaskReq): Promise<number>;
}