"use strict";

/* tslint:disable */
/* eslint-disable */

// Generated by thriftgo 0.4.2-HuiDu(v1.3)
// Source: test\typescript\test_expreq.thrift
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// 导入服务接口
import type { IExpreq } from './expreq';
import axios from '@/utils/request';
import { BizException } from "@/types/exception"

/**
 * Expreq Axios HTTP 客户端实现
 * 根据 Thrift 服务定义和 API 注解自动生成的 HTTP 请求实现
 * 支持使用项目中已实例化的 axios 实例
 */
export class ExpreqClient implements IExpreq {
  /**
   * add
   * API: GET [/add]
   * @param a a
   * @returns number
   */
  async add(a: TaskReq): Promise<number> {
    try {
      let url = '/add';

      let queryParams: any = {};
      
      if (a.pageReq !== undefined && a.pageReq !== null) {
        queryParams['pageReq'] = a.pageReq;
      }
      
      if (a.taskId !== undefined && a.taskId !== null) {
        queryParams['taskId'] = a.taskId;
      }
      let response = await axios.get(url, { params: queryParams });
      
      if (response.status >= 200 && response.status < 300) {
     	if (response.data.code !== 0) {
          throw new BizException(response.data.code, response.data.msg);
        }
        return response.data;
      } else {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }
    } catch (error) {
      console.error('add request failed:', error);
      throw error;
    }
  }
}