"use strict";

// Generated by thriftgo 0.4.2-HuiDu(v1.3)
// Source: test\typescript\test_expreq.thrift
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
export type { PageReq } from './pagereq';
export type { TaskReq } from './taskreq';
export type { IExpreq } from './expreq';
export { ExpreqClient } from './expreqclient';