// Copyright 2021 CloudWeGo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// either express or implied. See the License for the specific language governing
// permissions and limitations under the License.

package templates

const SimpleServiceImplementationTemplate = `
{{- define "simpleServiceImplementation" -}}
"use strict";

// Generated by thriftgo {{Version}}
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

{{- if .Imports }}
{{ template "imports" . }}
{{- end }}

{{- range .Services }}
// 导入服务接口
import { {{ GetInterfaceName .Name }} } from './{{ ToLower .Name }}';

/**
 * {{ GetInterfaceName .Name }} 异步接口
 * 用于 Axios 客户端等异步实现
 */
export interface Async{{ GetInterfaceName .Name }} {
{{- range .Functions }}
  {{ GetPropertyName .Name }}({{ range $index, $arg := .Arguments }}{{ if $index }}, {{ end }}{{ GetPropertyName .Name }}{{ if IsOptional . }}?{{ end }}: {{ GetFieldType . }}{{ end }}): Promise<{{ if .FunctionType }}{{ GetTypeScriptType .FunctionType }}{{ else }}void{{ end }}>;
{{- end }}
}

/**
 * {{ GetInterfaceName .Name }} Axios HTTP 客户端实现
 * 根据 Thrift 服务定义和 API 注解自动生成的 HTTP 请求实现
 * 支持使用项目中已实例化的 axios 实例
 */
export class {{ GetInterfaceName .Name }}AxiosClient implements Async{{ GetInterfaceName .Name }} {
  private axios: any;
  private baseURL: string;

  constructor(baseURL?: string, axiosInstance?: any) {
    // 优先使用传入的 baseURL，然后尝试环境变量，最后使用默认值
    this.baseURL = baseURL || 
      (typeof process !== 'undefined' && process.env && process.env.API_BASE_URL) ||
      (typeof window !== 'undefined' && (window as any).__API_BASE_URL__) ||
      'http://localhost:8080';
    if (axiosInstance) {
      // 使用传入的 axios 实例，设置 baseURL
      this.axios = axiosInstance;
      if (axiosInstance.defaults) {
        axiosInstance.defaults.baseURL = this.baseURL;
      }
    } else {
      // 尝试动态导入 axios
      try {
        // 优先尝试 ES 模块导入
        this.axios = eval('import')('axios').then(axios => {
          const axiosInstance = axios.default || axios;
          axiosInstance.defaults.baseURL = this.baseURL;
          return axiosInstance;
        });
      } catch (error) {
        try {
          // 回退到 CommonJS require
          const axios = eval('require')('axios');
          axios.defaults.baseURL = this.baseURL;
          this.axios = axios;
        } catch (requireError) {
          throw new Error('Axios is not installed. Please run: npm install axios');
        }
      }
    }
  }
{{- range .Functions }}
  /**
   * {{ .Name }}
{{- if .Annotations.Get "api.get" }}
   * API: GET {{ .Annotations.Get "api.get" }}
{{- else if .Annotations.Get "api.post" }}
   * API: POST {{ .Annotations.Get "api.post" }}
{{- else if .Annotations.Get "api.put" }}
   * API: PUT {{ .Annotations.Get "api.put" }}
{{- else if .Annotations.Get "api.delete" }}
   * API: DELETE {{ .Annotations.Get "api.delete" }}
{{- end }}
{{- range .Arguments }}
   * @param {{ GetPropertyName .Name }} {{ .Name }}
{{- end }}
{{- if .FunctionType }}
   * @returns {{ GetTypeScriptType .FunctionType }}
{{- else }}
   * @returns void
{{- end }}
   */
  async {{ GetPropertyName .Name }}({{ range $index, $arg := .Arguments }}{{ if $index }}, {{ end }}{{ GetPropertyName .Name }}{{ if IsOptional . }}?{{ end }}: {{ GetFieldType . }}{{ end }}): Promise<{{ if .FunctionType }}{{ GetTypeScriptType .FunctionType }}{{ else }}void{{ end }}> {
    try {
      let url = '{{ if .Annotations.Get "api.get" }}{{ index (.Annotations.Get "api.get") 0 }}{{ else if .Annotations.Get "api.post" }}{{ index (.Annotations.Get "api.post") 0 }}{{ else if .Annotations.Get "api.put" }}{{ index (.Annotations.Get "api.put") 0 }}{{ else if .Annotations.Get "api.delete" }}{{ index (.Annotations.Get "api.delete") 0 }}{{ end }}';
{{- range $index, $arg := .Arguments }}
{{- end }}

{{- range $argIndex, $arg := .Arguments }}
{{- if $arg.Annotations.Get "api.path" }}
{{- $pathValue := index ($arg.Annotations.Get "api.path") 0 }}
{{- if $pathValue }}
      if ({{ GetPropertyName $arg.Name }} !== undefined && {{ GetPropertyName $arg.Name }} !== null) {
        url = url.replace(String('{'+'{{ $pathValue }}'+'}'), String({{ GetPropertyName $arg.Name }}));
      }
{{- end }}
{{- end }}
{{- end }}

{{- range $argIndex, $arg := .Arguments }}
{{- if IsStructField $arg }}
{{- $structAnnotations := GetStructFieldAnnotationsForTemplate $arg }}
{{- range $fieldName, $fieldAnnotations := $structAnnotations }}
{{- if index $fieldAnnotations "api.path" }}
{{- $pathValue := index $fieldAnnotations "api.path" }}
{{- if $pathValue }}
      if ({{ GetPropertyName $arg.Name }}.{{ $fieldName }} !== undefined && {{ GetPropertyName $arg.Name }}.{{ $fieldName }} !== null) {
        url = url.replace(String('{'+'{{ $pathValue }}'+'}'), String({{ GetPropertyName $arg.Name }}.{{ $fieldName }}));
      }
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- range $argIndex, $arg := .Arguments }}
      {{- if not (IsStructField $arg) }}
      if (url.includes('{'+'{{ GetPropertyName $arg.Name }}'+'}')) {
        url = url.replace(String('{'+'{{ GetPropertyName $arg.Name }}'+'}'), String({{ GetPropertyName $arg.Name }}));
      }
      {{- end }}
{{- end }}

      let queryParams: any = {};

{{- range $argIndex, $arg := .Arguments }}
{{- if $arg.Annotations.Get "api.query" }}
{{- $queryValue := index ($arg.Annotations.Get "api.query") 0 }}
{{- if $queryValue }}
      if ({{ GetPropertyName $arg.Name }} !== undefined && {{ GetPropertyName $arg.Name }} !== null) {
        queryParams['{{ $queryValue }}'] = {{ GetPropertyName $arg.Name }};
      }
{{- end }}
{{- end }}
{{- end }}

{{- range $argIndex, $arg := .Arguments }}
{{- if IsStructField $arg }}
{{- $structAnnotations := GetStructFieldAnnotationsForTemplate $arg }}
{{- range $fieldName, $fieldAnnotations := $structAnnotations }}
{{- if index $fieldAnnotations "api.query" }}
{{- $queryValue := index $fieldAnnotations "api.query" }}
{{- if $queryValue }}
      if ({{ GetPropertyName $arg.Name }}.{{ $fieldName }} !== undefined && {{ GetPropertyName $arg.Name }}.{{ $fieldName }} !== null) {
        queryParams['{{ $queryValue }}'] = {{ GetPropertyName $arg.Name }}.{{ $fieldName }};
      }
{{- end }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
      {{- $apiMethod := "" }}
      {{- if .Annotations.Get "api.get" }}
      {{- $apiMethod = "GET" }}
      {{- else if .Annotations.Get "api.post" }}
      {{- $apiMethod = "POST" }}
      {{- else if .Annotations.Get "api.put" }}
      {{- $apiMethod = "PUT" }}
      {{- else if .Annotations.Get "api.delete" }}
      {{- $apiMethod = "DELETE" }}
      {{- end }}

      {{- if or (eq $apiMethod "POST") (eq $apiMethod "PUT") }}
      let bodyParam = {};
      
      {{- range $argIndex, $arg := .Arguments }}
      {{- if and (IsStructField $arg) ($arg.Annotations.Get "api.body") }}
      {{- $structAnnotations := GetStructFieldAnnotationsForTemplate $arg }}
      {{- range $fieldName, $fieldAnnotations := $structAnnotations }}
      {{- if not (index $fieldAnnotations "api.query") }}
      {{- if not (index $fieldAnnotations "api.path") }}
      if ({{ GetPropertyName $arg.Name }}.{{ $fieldName }} !== undefined && {{ GetPropertyName $arg.Name }}.{{ $fieldName }} !== null) {
        bodyParam['{{ $fieldName }}'] = {{ GetPropertyName $arg.Name }}.{{ $fieldName }};
      }
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}

      {{- if eq $apiMethod "GET" }}
      {{- range $argIndex, $arg := .Arguments }}
      {{- if and (not ($arg.Annotations.Get "api.path")) (not ($arg.Annotations.Get "api.query")) (not ($arg.Annotations.Get "api.body")) }}
      {{- if IsStructField $arg }}
      {{- $structAnnotations := GetStructFieldAnnotationsForTemplate $arg }}
      {{- range $fieldName, $fieldAnnotations := $structAnnotations }}
      {{- if not (index $fieldAnnotations "api.query") }}
      
      if ({{ GetPropertyName $arg.Name }}.{{ $fieldName }} !== undefined && {{ GetPropertyName $arg.Name }}.{{ $fieldName }} !== null) {
        queryParams['{{ $fieldName }}'] = {{ GetPropertyName $arg.Name }}.{{ $fieldName }};
      }
      {{- end }}
      {{- end }}
      {{- else }}
      if ({{ GetPropertyName $arg.Name }} !== undefined && {{ GetPropertyName $arg.Name }} !== null && !url.includes('{'+'{{ GetPropertyName $arg.Name }}'+'}')) {
        queryParams['{{ GetPropertyName $arg.Name }}'] = {{ GetPropertyName $arg.Name }};
      }
      {{- end }}
      {{- end }}
      {{- end }}
      {{- else if or (eq $apiMethod "POST") (eq $apiMethod "PUT") }}
      {{- $hasBodyParam := false }}
      {{- range .Arguments }}
      {{- if .Annotations.Get "api.body" }}
      {{- $hasBodyParam = true }}
      {{- end }}
      {{- end }}
      {{- if not $hasBodyParam }}
      {{- range $argIndex, $arg := .Arguments }}
      {{- if and (not ($arg.Annotations.Get "api.path")) (not ($arg.Annotations.Get "api.query")) (not ($arg.Annotations.Get "api.body")) }}
      {{- if IsStructField $arg }}
      {{- $structAnnotations := GetStructFieldAnnotationsForTemplate $arg }}
      {{- range $fieldName, $fieldAnnotations := $structAnnotations }}
      {{- if not (index $fieldAnnotations "api.query") }}
      {{- if not (index $fieldAnnotations "api.path") }}
      if ({{ GetPropertyName $arg.Name }}.{{ $fieldName }} !== undefined && {{ GetPropertyName $arg.Name }}.{{ $fieldName }} !== null) {
        bodyParam['{{ $fieldName }}'] = {{ GetPropertyName $arg.Name }}.{{ $fieldName }};
      }
      {{- end }}
      {{- end }}
      {{- end }}
      {{- else }}
      if ({{ GetPropertyName $arg.Name }} !== undefined && {{ GetPropertyName $arg.Name }} !== null && !url.includes('{'+'{{ GetPropertyName $arg.Name }}'+'}')) {
        bodyParam['{{ GetPropertyName $arg.Name }}'] = {{ GetPropertyName $arg.Name }};
      }
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      
      
      const axiosInstance = await Promise.resolve(this.axios);
      
      {{- if eq $apiMethod "GET" }}
      let response = await axiosInstance.get(url, { params: queryParams });
      {{- else if eq $apiMethod "POST" }}
      let response = await axiosInstance.post(url, bodyParam, { params: queryParams });
      {{- else if eq $apiMethod "PUT" }}
      let response = await axiosInstance.put(url, bodyParam, { params: queryParams });
      {{- else if eq $apiMethod "DELETE" }}
      let response = await axiosInstance.delete(url, { params: queryParams });
      {{- end }}
      
      if (response.status >= 200 && response.status < 300) {
        return response.data;
      } else {
        throw new Error(` + "`" + `HTTP ${response.status}: ${response.statusText}` + "`" + `);
      }
    } catch (error) {
      console.error('{{ .Name }} request failed:', error);
      throw error;
    }
  }
{{- end }}
}
{{- end }}
{{- end -}}
`
